---

####################
# Create efs using Terraform
####################

- name: Create the physical EFS
  shell: |
    cd ../
    mkdir -p build/
    cp -r tf/* build/
    cd build/
    VARS_FILE="tfvars.sh"
    if [ -f $VARS_FILE ]; then
      echo "File $VARS_FILE exists."
      . ./$VARS_FILE
      accountid=`aws sts get-caller-identity --output text --query 'Account'`
      terraform init -reconfigure -backend=true -get=true -input=false \
      -backend-config="bucket=${accountid}-${TF_VAR_stack_name_prefix}-${TF_VAR_environment}-state-store" \
      -backend-config="region=${TF_VAR_region}"

      terraform apply -input=false -auto-approve > apply.txt
    else
      echo "File $VARS_FILE does not exist."
      exit 255
    fi