---

####################
# Create efs using Terraform
####################

- name: Create the physical EFS
  shell: |
    cd ../
    mkdir -p build/
    cp -r tf/* build/
    cd build/
    VARS_FILE="vars.list"
    if [ -f $VARS_FILE ]; then
      echo "File $VARS_FILE exists."
      . ./$VARS_FILE
      terraform init
      terraform apply > apply.txt
    else
      echo "File $VARS_FILE does not exist."
      exit 255
    fi